---
- name: Template
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Where am I?!
      ansible.builtin.shell: |
        source ~/.dotfiles/source.sh
        country
      args:
        executable: /bin/zsh
      register: country
    - debug: msg="{{ country.stdout }}"
