---
- name: Compile CRC using machine
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    env_name: "{{ env_name | default('crcbuild') }}"
  
  roles:
    - role: gbraad.dotfiles
    - role: gbraad.dotfiles-apps
      vars:
        name: "macadam"
    - role: gbraad.dotfiles-machine
      vars:
        name: "{{ env_name }}"
        command: "from golang"
 
  tasks:
    - name: Make clean and cross compile using machine
      ansible.builtin.shell: |
        source ~/.dotfiles/source.sh
        machine {{ env_name }} playbook {{ playbook_dir }}/compile.yml
      args:
        executable: /bin/zsh
