---
- name: Compile CRC on runner using devenv
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    devenv_prefix: "gofedora"
  
  roles:
    - role: gbraad.dotfiles
    - role: gbraad.dotfiles-devenv
      vars:
        prefix: "{{ devenv_prefix }}"
        command: noinit
 
  tasks:
    - name: Make clean and cross compile using devenv
      ansible.builtin.shell: |
        source ~/.dotfiles/source.sh
        devenv {{ devenv_prefix }} playbook {{ playbook_dir }}/compile.yml
      args:
        executable: /bin/zsh
