---
- name: Compile CRC on localhost
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    crc_repo_url: "https://github.com/crc-org/crc"
    devenv_projects_dir: "/home/gbraad/Projects"
    devenv_repo_dest: "{{ devenv_projects_dir }}/crc-org/crc"
  
  tasks:
    - name: Clone crc repo to ~/Projects/crc-org/crc
      ansible.builtin.git:
        repo: "{{ crc_repo_url }}"
        dest: "{{ devenv_repo_dest }}"
        version: main
        update: yes

    - name: Make clean and cross compile inside container
      ansible.builtin.shell: |
         cd {{ devenv_repo_dest }} && make clean && make cross
