---
- name: Compile using devenv
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    env_name: "{{ env_name | default('build') }}"
    env_from: "{{ env_from | default('gofedora') }}"
    playbook_name: "{{ playbook_name | default('recipes/crc.yml') }}"
  
  roles:
    - role: gbraad.dotfiles
    - role: gbraad.dotfiles-devenv
      vars:
        name: "{{ env_name }}"
        command: "from {{env_from }}"
 
  tasks:
    - name: Make clean and cross compile using devenv
      ansible.builtin.shell: |
        source ~/.dotfiles/source.sh
        devenv {{ env_name }} playbook {{ playbook_dir }}/{{ playbook_name }} -e target_user="gbraad"
        devenv {{ env_name }} 
      args:
        executable: /bin/zsh
