---
- name: Compile CRC on localhost
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    user: "{{ target_user | default(lookup('env', 'USER')) }}"
    crc_repo_url: "https://github.com/crc-org/crc"
    projects_dir: "/home/{{ user }}/Projects"
    repo_dest: "{{ projects_dir }}/crc-org/crc"
  
  tasks:
    - name: Clone crc repo
      ansible.builtin.git:
        repo: "{{ crc_repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        update: yes

    - name: Make clean and cross compile
      ansible.builtin.shell: |
         cd {{ repo_dest }} && make clean && make cross
