---
- name: Compile using machine
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    env_name: "{{ env_name | default('build', true) }}"
    env_from: "{{ env_from | default('golang', true) }}"
    playbook_name: "{{ playbook_name | default('recipes/crc.yml') }}"

  roles:
    - role: gbraad.dotfiles
    - role: gbraad.dotfiles-apps
      vars:
        name: "macadam"
    - role: gbraad.dotfiles-machine
      vars:
        name: "{{ env_name }}"
        command: "from {{ env_from }}"
 
  tasks:
    - name: Make clean and cross compile using machine
      ansible.builtin.shell: |
        source ~/.dotfiles/source.sh
        machine {{ env_name }} playbook {{ playbook_dir }}/{{ playbook_name }} -e target_user="gbraad"
        machine {{ env_name }} rm
      args:
        executable: /bin/zsh
