name: Compile CRC - playbook devenv

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-playbook-devenv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This folder will be used with the container
      - name: Create userdirs
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects

      # Install dotfiles from upstream
      - name: Setup dotfiles environment
        uses: gbraad-dotfiles/install-action@main
        with:
          upstream: true

      - name: Run devenv command - start
        id: devenv
        uses: gbraad-dotfiles/devenv-action@main
        with:
          prefix: gofedora
          command: start

      - name: Run devenv command - compile CRC
        uses: gbraad-dotfiles/devenv-action@main
        with:
          prefix: ${{ steps.devenv.outputs.prefix }}
          command: playbook ./compile-crc/compile-as-gbraad.yml

      - name: Upload Artifact - out
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: crc-out
          path: ${{ github.workspace }}/Projects/crc-org/crc/out
          retention-days: 1
          include-hidden-files: true
  