name: Compile CRC - devenv on runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-devenv-runner:
    runs-on: ubuntu-latest

    env:
      NAME: crcbuild
      PLAYBOOK: "recipes/crc.yml"
      OUT_PATH: "Projects/crc-org/crc/out"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create userdirs
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy install -r requirements.yml

      - name: Setup dotfiles environment (upstream)
        run: |
          ansible-playbook install-dotfiles/upstream.yml

      - name: Run Ansible Playbook - compile
        run: |
          ansible-playbook compile/compile-using-devenv.yml -e env_name="${{ env.NAME }}" -e playbook_name="${{ env.PLAYBOOK }}"

      - name: Upload Artifact - out
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ${{ github.workspace }}/${{ env.OUT_PATH}}
          retention-days: 1
          include-hidden-files: true
