name: Compile CRC - machine on runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-machine-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create userdirs 
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy install -r requirements.yml

      - name: Setup dotfiles environment (upstream)
        run: |
          ansible-playbook install-dotfiles/upstream.yml

      - name: Write machinekey to access the VM
        uses: gbraad-dotfiles/machinekey-action@main
        with:
          ssh_private_key: ${{ secrets.SSH_MACHINE_PRIVATE }}
          ssh_public_key: ${{ secrets.SSH_MACHINE_PUBLIC }}

      - name: Install required virtualization software
        continue-on-error: true
        uses: gbraad-actions/setup-virtualization@v3
      
      - name: Run Ansible Playbook
        run: |
          ansible-playbook compile-crc/compile-using-machine.yml

      - name: Run machine command - Copy artifacts out of the VM using SSH
        uses: gbraad-dotfiles/machine-action@main
        with:
          prefix: crcbuild
          command: exec
          args: tar cf - Projects/crc-org/crc/out/ | tar xf -

      - name: Upload Artifact - out
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: crc-out
          path: ${{ github.workspace }}/Projects/crc-org/crc/out
          retention-days: 1
          include-hidden-files: true
