name: Compile using playbook on runner

on:
  workflow_call:
    inputs:
      playbook:
        required: true
        type: string
      out_path:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      playbook:
        required: true
        type: string
      out_path:
        required: true
        type: string

jobs:
  test-playbook-runner:
    runs-on: ubuntu-latest

    env:
      PLAYBOOK: ${{ inputs.playbook }}
      OUT_PATH: ${{ inputs.out_path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This folder will be used with the container
      - name: Create userdirs
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects

      # Install dotfiles from upstream
      - name: Setup dotfiles environment
        uses: gbraad-dotfiles/install-action@main
        with:
          upstream: true

      - name: Setup ansible
        uses: gbraad-actions/setup-ansible@v1

      - name: Run Ansible Playbook - compile
        uses: gbraad-dotfiles/playbook-action@main
        with:
          playbook: compile/${{ env.PLAYBOOK }}
          command: execute

      - name: Upload Artifact - out
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ${{ github.workspace }}/${{ env.OUT_PATH }}
          retention-days: 1
          include-hidden-files: true
