name: Compile using machine on runner

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        default: "build"
      environment_from:
        type: string
        default: "golang"
      playbook:
        required: true
        type: string
      out_name:
        required: true
        type: string
        default: "uploads"
      out_path:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment_name:
        type: string
        default: "build"
      environment_from:
        type: string
        default: "golang"
      playbook:
        required: true
        type: string
      out_name:
        required: true
        type: string
        default: "uploads"
      out_path:
        required: true
        type: string

jobs:
  test-machine-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create userdirs 
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects
          mkdir -p Uploads
          ln -s ${{ github.workspace }}/Uploads  ${HOME}/Uploads

      - name: Setup ansible
        uses: gbraad-actions/setup-ansible@v1

      - name: Setup dotfiles environment (upstream)
        run: |
          ansible-galaxy install -r requirements.yml
          ansible-playbook install-dotfiles/upstream.yml

      - name: Write machinekey to access the VM
        uses: gbraad-dotfiles/machinekey-action@main
        with:
          ssh_private_key: ${{ secrets.SSH_MACHINE_PRIVATE }}
          ssh_public_key: ${{ secrets.SSH_MACHINE_PUBLIC }}

      - name: Install required virtualization software
        continue-on-error: true
        uses: gbraad-actions/setup-virtualization@v3
      
      - name: Run Ansible Playbook - compile
        uses: gbraad-dotfiles/playbook-action@main
        with:
          playbook: compile/compile-using-machine.yml
          command: execute
          args: -e env_name="${{ inputs.environment_name }}" -e env_from="${{ inputs.environment_from }}" -e playbook_name="${{ inputs.playbook }}"

      - name: Prepare artifacts uploads folder
        run: |
          mkdir -p ${HOME}/Uploads/${{ inputs.out_name }}

      - name: Run machine command - Copy artifacts out of the VM using SSH
        uses: gbraad-dotfiles/machine-action@main
        with:
          prefix: ${{ inputs.environment_name }}
          command: exec
          args: tar cf - ${{ inputs.out_path }} | tar xf - -C ${HOME}/Uploads/${{ inputs.out_name }}

      - name: Upload Artifact - uploads
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.out_name }}
          path: ${{ github.workspace }}/Uploads/
          retention-days: 1
          include-hidden-files: true
