name: Compile using playbook on devenv

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        default: "build"
      environment_from:
        type: string
        default: "gofedora"
      playbook:
        required: true
        type: string
      out_name:
        required: true
        type: string
        default: "uploads"
      out_path:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment_name:
        type: string
        default: "build"
      environment_from:
        type: string
        default: "gofedora"
      playbook:
        required: true
        type: string
      out_name:
        required: true
        type: string
        default: "uploads"
      out_path:
        required: true
        type: string

jobs:
  test-playbook-devenv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This folder will be used with the container
      - name: Create userdirs
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects
          mkdir -p Uploads
          ln -s ${{ github.workspace }}/Uploads  ${HOME}/Uploads

      # Install dotfiles from upstream
      - name: Setup dotfiles environment
        uses: gbraad-dotfiles/install-action@main
        with:
          upstream: true

      - name: Run devenv command - start container
        id: devenv
        uses: gbraad-dotfiles/devenv-action@main
        with:
          prefix: ${{ inputs.environment_name }}
          command: from ${{ inputs.environment_from }}

      - name: Run devenv command - compile
        uses: gbraad-dotfiles/devenv-action@main
        with:
          prefix: ${{ steps.devenv.outputs.prefix }}
          command: playbook ./compile/${{ inputs.playbook }} -e target_user="gbraad"

      - name: Copy artifacts to the uploads folder
        run: |
          mkdir -p ${HOME}/Uploads/${{ inputs.out_name }}
          cp -r ${{ inputs.out_path }}/* ${HOME}/Uploads/${{ inputs.out_name }}

      - name: Remove build environment
        uses: gbraad-dotfiles/devenv-action@main
        with:
          prefix: ${{ steps.devenv.outputs.prefix }}
          command: rm

      - name: Upload Artifact - uploads
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.out_name }}
          path: ${{ github.workspace }}/Uploads/
          retention-days: 1
          include-hidden-files: true
